function res = catalogueM(x,y)
    D = det([ 1 x(1) y(1) ;...
              1 x(2) y(2) ;...
              1 x(3) y(3) ]);
          
    A = [ 2 1 1 ;...
          1 2 1 ;...
          1 1 2 ];
    
    res = D*A/24;
end